# Generated by Django 6.0.4 on 2026-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair'), ('barber', 'Barber'), ('nails', 'Nails'), ('makeup', 'Makeup'), ('spa', 'Spa'), ('facial', 'Facial'), ('waxing', 'Waxing')], default='hair', max_length=50),
        ),
    ]
