# Generated by Django 6.0.4 on 2026-05-13 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hairdresser', 'Hairdresser'), ('barber', 'Barber'), ('nail_technician', 'Nail Technician'), ('makeup_artist', 'Makeup Artist'), ('receptionist', 'Receptionist')], max_length=50)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Bridal Hair, Beard Trimming', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('expertise_years', models.IntegerField(default=1, help_text='Years of experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__first_name'],
            },
        ),
    ]
