# Generated by Django 6.0.4 on 2026-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_appointment_assigned_staff_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Force password change on next login'),
        ),
    ]
