# Generated by Django 6.0.4 on 2026-06-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_staff_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_available',
        ),
        migrations.AddField(
            model_name='staff',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
