# Generated by Django 6.0.4 on 2026-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_remove_staff_is_available_staff_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('hairdresser', 'Hairdresser'), ('barber', 'Barber'), ('nail_technician', 'Nail Technician'), ('makeup_artist', 'Makeup Artist'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier')], max_length=50),
        ),
    ]
