# Generated by Django 6.0.4 on 2026-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_payment_checkout_request_id_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('salaries', 'Salaries'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('hair_products', 'Hair Products'), ('nail_products', 'Nail Products'), ('makeup_products', 'Makeup Products'), ('cleaning_supplies', 'Cleaning Supplies'), ('marketing', 'Marketing'), ('equipment', 'Equipment'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair Services'), ('barber', 'Barber Services'), ('makeup', 'Makeup Services'), ('nails', 'Nail Services'), ('facial', 'Facial & Beauty'), ('spa', 'Spa & Wellness')], default='hair', max_length=50),
        ),
    ]
