# Generated by Django 6.0.4 on 2026-06-05 08:44

from django.db import migrations

SPECIALIZATION_MAP = {
    'barber': 'Haircuts, Fades, Beard Grooming, Eyebrow Shaping',
    'hair_stylist': 'Haircuts, Blow-dry, Coloring, Styling, Treatments',
    'nail_technician': 'Manicure, Pedicure, Nail Art, Gel Nails',
    'makeup_artist': 'Bridal Makeup, Evening Makeup, Airbrush, HD Makeup',
    'beautician': 'Facials, Waxing, Threading, Skin Treatments',
    'spa_therapist': 'Massage, Body Scrub, Aromatherapy, Steam Bath',
    'cashier': 'Payment Processing, Billing, POS Operations',
    'receptionist': 'Booking Management, Customer Service, Front Desk',
}

ROLE_MAP = {
    'hairdresser': 'hair_stylist',
    'barber': 'barber',
    'nail_technician': 'nail_technician',
    'makeup_artist': 'makeup_artist',
    'receptionist': 'receptionist',
    'cashier': 'cashier',
}

def migrate_roles(apps, schema_editor):
    Staff = apps.get_model('salon', 'Staff')
    for staff in Staff.objects.all():
        old_role = staff.role
        staff.role = ROLE_MAP.get(old_role, old_role)
        if not staff.specialization:
            staff.specialization = SPECIALIZATION_MAP.get(staff.role, '')
        staff.save()


def reverse_migrate_roles(apps, schema_editor):
    Staff = apps.get_model('salon', 'Staff')
    reverse_map = {v: k for k, v in ROLE_MAP.items()}
    for staff in Staff.objects.all():
        if staff.role in reverse_map:
            staff.role = reverse_map[staff.role]
        staff.save()


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_expense_category_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
